services:
  finecon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finecon_app
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./uploads:/app/uploads
      - next_cache:/app/.next/cache

volumes:
  next_cache: