services:
  finecon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finecon_app
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - /app/node_modules
    networks:
      - finecon_network

networks:
  finecon_network:
    driver: bridge